<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GeradorWebConfig.Application\GeradorWebConfig.Application.csproj" />
    <ProjectReference Include="..\GeradorWebConfig.Domain\GeradorWebConfig.Domain.csproj" />
  </ItemGroup>

</Project>
